

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: collegeApp
    ports:
      - "5432:5432" # Exposes PostgreSQL to the host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" # pgAdmin available on localhost:8081
    depends_on:
      - postgres-db # Ensures PostgreSQL starts before pgAdmin
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge